#include "Ficha.h"




Integer Ficha::getFila()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AC7 begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AC7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Integer Ficha::getColumna()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AC9 begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AC9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Pareja Ficha::getPareja()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000ACB begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000ACB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ficha::setFila()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000ACD begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000ACD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ficha::setColumna()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000ACF begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000ACF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Ficha::setPareja()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AD1 begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AD1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
