#include "Juego.h"




void Juego::getJugadores()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AE2 begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AE2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Juego::agregarJugador()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AE4 begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AE4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Juego::agregarPila()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AE6 begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AE6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
