#include "Pila_Cartas.h"




Boolean Pila_Cartas::push()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000A9B begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000A9B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Carta &Pila_Cartas::pop()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000A9D begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000A9D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Pila_Cartas::shuffle()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000A9F begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000A9F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
