#include "Tablero.h"




Ficha Tablero::getFicha()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AAD begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AAD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Ficha Tablero::getFichas()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AAF begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AAF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Carta &Tablero::getCarta()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AB1 begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AB1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Carta &Tablero::getCartas()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AB3 begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AB3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Tablero::limpiar()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AD3 begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AD3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Tablero::agregarFicha()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AD5 begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AD5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Tablero::agregarCarta()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AD7 begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AD7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Tablero::removerFicha()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AD9 begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000AD9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Tablero::removerCarta()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000ADB begin
{
}
// section 127-0-1-1-7cfaeb29:1414b2d8874:-8000:0000000000000ADB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
